Repository Olanetsoft/web3terms, pull requests merged in 2022-10, with the labels that each got.

#43 Update terms.json
  data/terms.json
Labels: enhancement, hacktoberfest

#46 Fix: Fixed all the terms without tag
  data/terms.json
Labels: bug, enhancement, hacktoberfest

#45 Added sorting mechanism
  README.md
  bin/sort.js
  data/terms.json
  package.json
Labels: enhancement, hacktoberfest

#53 Update
  data/terms.json
Labels: bug, hacktoberfest

#54 Feat: Enhanced Readme.md file with Valuable Suggestions
  README.md
Labels: enhancement, good first issue, hacktoberfest

#56 Added More Web3 Terminologies for issue:#32
  data/terms.json
Labels: enhancement, hacktoberfest

#57 Fix: Format README.md
  README.md
Labels: enhancement, hacktoberfest

#58 Added some more web 3 terms
  data/terms.json
Labels: enhancement, hacktoberfest

#59 trimmed all web3 terms to less than 280 characters
  data/terms.json
Labels: bug, enhancement, hacktoberfest

#60 Added a term "EPNS"
  data/terms.json
Labels: enhancement, hacktoberfest

#63 Added 3 different ERC tokens
  data/terms.json
Labels: enhancement, hacktoberfest

#70 Implemented Endpoint to retrieve all terms
  README.md
  controllers/termsController.js
  data/terms.json
  routes/terms.js
  services/terms.js
Labels: documentation, enhancement, good first issue, hacktoberfest

#71 Merge `develop` branch to `main`
  .babelrc
  .eslintrc.json
  README.md
  bin/sort.js
  contributing.md
  controllers/termsController.js
  data/terms.json
  index.js
  package.json
  pull_request_template.md
  routes/terms.js
  services/terms.js
  test/term-definition-length.test.js
  web3terms.postman_collection.json
  yarn.lock
Labels: bug, documentation, enhancement, hacktoberfest

#73 Add term offchain
  data/terms.json
Labels: enhancement

#76 feat: add test workflow
  .github/workflows/lint.yml
  .github/workflows/test.yml
  data/terms.json
  package.json
  test/term-definition-length.test.js
  test/terms.test.js
Labels: bug, enhancement, hacktoberfest

#82 Adding ZK-rollups meaning
  data/terms.json
Labels: documentation, enhancement, hacktoberfest

#87 Add 3 new terms
  data/terms.json
Labels: documentation, enhancement, hacktoberfest
